### ISSUE TITLE
Windows環境安裝python coco package的解決方法

### ISSUE THREAD

**Issue by WadeTsai** [erhwenkuo/deep-learning-with-keras-notebooks#2]
在Windows下執行 python setup.py build_ext install
如遇到 cl : Command line error D8021 : invalid numeric argument '/Wno-cpp' 的錯誤
只要修改setup.py
更改 xtra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],
為 extra_compile_args={'gcc': ['/Qstd=c99']},
即可順利安裝

**Comment by erhwenkuo** [comment]
謝謝你的訊息。

Wade Tsai <notifications@github.com>於 2018年2月6日 週二，下午6:56寫道：
