### ISSUE TITLE
English

### ISSUE THREAD

**Issue by Iqlaas** [erhwenkuo/deep-learning-with-keras-notebooks#3]
Hi there ! Great work. 

Just asking, will you be able to translate this repo to english ?

I am a beginner and I found your repo very informational.

Hope you will consider this.

Thank you!

**Comment by erhwenkuo** [comment]
Hi Iqlass
Thanks you for your compliment of this repo. So far I haven't plan to translate these practices to English. I believe you can find most the material in English base on the reference link I put at the end of each notebook. The reason I wrote these notebook in Chinese is I think there are too few Chinese deep learning contents compare to English.
